### ISSUE TITLE
Error 01

### ISSUE THREAD

**Issue by louissosthenes9** [Mdsoln/EntrepNet#6]
endpoint: "http://localhost:8080/api/v1/user/register",

payload: {"firstname":"teu","surname":"sssssss","mobile":984923745,"psw":"5=KvQ%@B9Q}egLu","email":"dddd@gmail.com"}

error: Network Error,

desc:  Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://localhost:8080/api/v1/user/register. (Reason: CORS request did not succeed). Status code: (null)

**Comment by Mdsoln** [comment]
cors error resolved already
