### ISSUE TITLE
Documentation of chatting endpoints

### ISSUE THREAD

**Issue by louissosthenes9** [Mdsoln/EntrepNet#8]
- I'm going to send you a payload of the message(just a text)  with sender's and receiver's id on query params ......I expect you to return me created at, the message it self and id of the participants..
- I expect to have an endpoint that returns the existing messages between users...one on queryparams ....the other on the request object
- I need an endpoints the fetch chats or conversations

**Comment by Mdsoln** [comment]
navigate through chatapp folder, then go chat-explanation
